title:             Kiwi
email:             kiwimatkiwi@gmail.com
description:       Feeding Kiwi Properly
author:            KiwiMatKiwi
baseurl:           "/kiwi-blog"
url:               "http://kiwimatkiwi.github.io"

# Social Profiles
twitter_username:  twitter_username
github_username:   github_username
facebook_username: facebook_username

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
